ALTER TABLE saved_sets ADD MONSTER VARCHAR(1024);
ALTER TABLE saved_sets ADD WEAPON VARCHAR(1024);
ALTER TABLE saved_sets ADD PURPOSE VARCHAR(1024);

drop table if exists armour_skills;
CREATE TABLE armour_skills (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         ARMOUR_NAME VARCHAR(1024) NOT NULL,
         ARMOUR_PIECE INT NOT NULL,
         SKILL_NAME VARCHAR(1024) NOT NULL,
         SKILL_VALUE INT NOT NULL,
         MH_VERSION INT NOT NULL,
         RANK INT NOT NULL
       );