DROP TABLE IF EXISTS set_skills;
DROP TABLE IF EXISTS user_votes CASCADE;
DROP TABLE IF EXISTS saved_sets;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS armour_skills;

CREATE TABLE saved_sets (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         USER_ID BIGINT,
         MH_VERSION INT NOT NULL,
         NUM_UP_VOTES INT DEFAULT 0,
         NUM_DOWN_VOTES INT DEFAULT 0,
         LABEL VARCHAR(512),
         CODE VARCHAR(1024),
         NUM_WEAPON_SLOTS INTEGER, 
         OWNER VARCHAR(1024),
         IP_ADDRESS VARCHAR(100),
         MONSTER VARCHAR(1024),
         WEAPON VARCHAR(1024),
         PURPOSE VARCHAR(1024)
       );

CREATE TABLE set_skills (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         LABEL VARCHAR(512),
         SAVED_SET_ID  BIGINT         
       );

CREATE TABLE users (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         USERNAME VARCHAR(1024) NOT NULL,
         PASSWORD VARCHAR(1024) NOT NULL
       );

CREATE TABLE user_votes (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         IP_ADDRESS VARCHAR(1024) NOT NULL,
         USER_ID BIGINT,
         ACTION VARCHAR(12) NOT NULL,
         SET_ID BIGINT NOT NULL
       );

CREATE TABLE armour_skills (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         ARMOUR_NAME VARCHAR(1024) NOT NULL,
         ARMOUR_PIECE INT NOT NULL,
         ARMOUR_ID INT NOT NULL,
         SKILL_NAME VARCHAR(1024) NOT NULL,
         SKILL_VALUE INT NOT NULL,
         MH_VERSION INT NOT NULL,
         RANK INT NOT NULL,
         GENDER VARCHAR(1),
         BLADE_OR_GUNNER VARCHAR(3)
       );
       
 CREATE TABLE monster_sets (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         MONSTER_NAME VARCHAR(1024) NOT NULL,
         ARMOUR_PIECE INT NOT NULL,
         ARMOUR_ID INT NOT NULL,
         MH_VERSION INT NOT NULL
       );

ALTER TABLE user_votes ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE user_votes ADD FOREIGN KEY (SET_ID) REFERENCES SAVED_SETS(ID);

ALTER TABLE set_skills ADD FOREIGN KEY (SAVED_SET_ID) REFERENCES SAVED_SETS(ID);
ALTER TABLE saved_sets ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);