insert into saved_sets (label, code, owner) values ('Darasu''s GS/Hammer Set', 'Darasu''s%20GS/Hammer%20Set%20:%20H.B.H.69.1.121.C.87.1.120.A.68.1.120.W.76.2.120.120.L.20.1.120.X.2.120.111.Y.0.1.13.6.0', 'Darasu');
insert into saved_sets (label, code, owner) values ('Oz78''s sharp Set', 'Oz78''s%20sharp%20Set%20:%20H.B.H.112.0.C.103.0.A.92.1.60.W.108.0.L.62.0', 'Oz78');
insert into saved_sets (label, code, owner) values ('Uzi''s bear Set', 'Uzi''s%20bear%20Set%20:%20H.B.H.63.1.102.C.68.1.87.A.61.1.88.W.69.1.88.L.68.1.88.Y.0.2.78.7.26.10.0', 'Uzi');
insert into saved_sets (label, code, owner) values ('MidnightManiac''s Set', 'MidnightManiac''s%20Set%20:%20H.B.H.97.2.88.87.C.103.0.A.41.1.87.W.43.0.L.42.0.X.1.87.Y.2.1.21.6.1.88', 'MidnightManiac');
insert into saved_sets (label, code, owner) values ('Tifa''s Medic Set', 'Tifa''s%20Medic%20Set%20:%20H.B.H.111.0.C.79.1.7.A.72.1.7.W.80.0.L.78.1.98.X.1.84.Y.2.1.60.7.1.84', 'Tifa');
insert into saved_sets (label, code, owner) values ('Moropa''s GS Draw Set', 'Moropa''s%20GS%20Draw%20Set%20:%20H.B.H.95.1.121.C.103.0.A.88.1.121.W.108.0.L.42.0.X.1.60.Y.1.2.13.7.53.3.1.106', 'Moropa');
insert into saved_sets (label, code, owner) values ('Moropa''s Ala Sleep Bombing Set', 'Moropa''s%20Ala%20Sleep%20Bombing%20Set%20:%20H.B.H.91.1.71.C.66.1.71.A.90.3.71.71.71.W.67.1.49.L.66.1.49.Y.1.1.69.10.1.49', 'Moropa');
insert into saved_sets (label, code, owner) values ('Moropa''s Speed Bombing Set', 'Moropa''s%20Speed%20Bombing%20Set%20:%20H.B.H.117.3.49.49.49.C.103.0.A.96.0.W.43.0.L.42.0.Y.2.1.69.10.2.49.49', 'Moropa');
insert into saved_sets (label, code, owner) values ('Moropa''s Gunner Sleep Bombing Set', 'Moropa''s%20Gunner%20Sleep%20Bombing%20Set%20:%20H.G.H.92.1.71.C.98.1.71.A.91.2.46.71.W.97.1.71.L.95.2.46.45.X.1.71.Y.2.1.69.10.1.46', 'Moropa');
insert into saved_sets (label, code, owner) values ('No''s Lance Set', 'No''s%20Lance%20Set%20:%20H.B.H.103.0.C.99.1.82.A.102.0.W.102.1.17.L.106.1.55.X.1.53.Y.2.1.32.7.1.25', 'No');
insert into saved_sets (label, code, owner) values ('No''s Hammer Set', 'No''s%20Hammer%20Set%20:%20H.B.H.97.1.115.C.103.0.A.98.1.115.W.43.0.L.42.0.X.1.16.Y.2.1.69.10.2.60.60', 'No');
insert into saved_sets (label, code, owner) values ('dr00''s burning offer Set', 'dr00''s%20burning%20offer%20Set%20:%20H.B.H.112.0.C.105.1.14.A.98.1.102.W.104.1.114.L.102.0.Y.1.2.78.6.61.3.1.101', 'dr00');
insert into saved_sets (label, code, owner) values ('Yuffie''s Naked Set', 'Yuffie''s%20Naked%20Set%20:%20H.B.H.99.2.107.114.C.113.1.115.A.106.3.23.23.23.W.108.0.L.76.1.23.Y.1.2.13.7.5.3.1.23', 'Yuffie');
insert into saved_sets (label, code, owner) values ('Yuffie''s Fav Set', 'Yuffie''s%20Fav%20Set%20:%20H.B.H.99.1.115.C.50.0.A.98.3.23.23.23.W.75.1.12.L.102.0.Y.2.1.69.10.1.12', 'Yuffie');
insert into saved_sets (label, code, owner) values ('Tifa''s SnS Status Set', 'Tifa''s%20SnS%20Status%20Set%20:%20H.B.H.99.2.88.23.C.101.2.88.23.A.76.2.88.23.W.67.1.23.L.66.1.23.Y.1.1.21.6.1.45', 'Tifa');
insert into saved_sets (label, code, owner) values ('Very Sharp Set', 'Very%20Sharp%20Set%20:%20H.B.H.103.0.C.109.0.A.102.0.W.104.1.16.L.66.1.53.X.1.54.Y.0.2.34.4.6.-10.0', 'No Name');
insert into saved_sets (label, code, owner) values ('Low Rank HGE S+1 Set', 'Low%20Rank%20HGE S%2B1%20Set%20:%20L.B.H.41.0.C.32.1.16.A.41.1.16.W.43.0.L.42.0.X.1.58.Y.2.0.2.60.60', 'No Name');
insert into saved_sets (label, code, owner) values ('Status only gunning set', 'Status%20only%20gunning%20set%20:%20H.G.H.113.0.C.102.1.55.A.99.2.54.30.W.97.1.30.L.85.1.53.X.1.53.Y.3.0.1.55', 'No Name');
insert into saved_sets (label, code, owner) values ('status only (poison) set', 'status%20only%20(poison)%20set%20:%20H.G.H.113.0.C.69.1.96.A.58.2.96.96.W.97.1.96.L.79.1.22.X.1.96.Y.0.1.22.7.0', 'No Name');
insert into saved_sets (label, code, owner) values ('aul ce+3 sharpner set', 'aul ce%2B3%20sharpner%20set%20:%20H.B.H.59.1.54.C.62.1.21.A.31.0.W.35.0.L.38.0.X.1.23.Y.1.1.1.7.1.23', 'No Name');

insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Darasu''s GS/Hammer Set'), 'Capture Expert');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Darasu''s GS/Hammer Set'), 'Focus');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Darasu''s GS/Hammer Set'), 'Ice Res +10');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Darasu''s GS/Hammer Set'), 'Critical Draw');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Darasu''s GS/Hammer Set'), 'Punishing Draw');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Oz78''s sharp Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Oz78''s sharp Set'), 'Mind''s Eye');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Oz78''s sharp Set'), 'Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Windproof (Hi)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Mud/Snow');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Speed Eating +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Tremor-Proof');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Fire Res +10');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Uzi''s bear Set'), 'Evasion +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'MidnightManiac''s Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'MidnightManiac''s Set'), 'HG Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'MidnightManiac''s Set'), 'Evasion +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s Medic Set'), 'Wide-Range +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s Medic Set'), 'Speed Eating +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s Medic Set'), 'Negate Stun');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s Medic Set'), 'Recovery Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s GS Draw Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s GS Draw Set'), 'Punishing Draw');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s GS Draw Set'), 'Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s GS Draw Set'), 'Critical Draw');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Status Atk Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Bombardier');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Razor Sharp');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Trap Master');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Heat Cancel (Lo)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Ala Sleep Bombing Set'), 'Double Poison');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Speed Bombing Set'), 'HG Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Speed Bombing Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Speed Bombing Set'), 'Trap Master');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Speed Bombing Set'), 'Bombardier');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Recoil Down +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Defense Up (s)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Bombardier');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Trap Master');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Heat Cancel (Lo)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Status Atk Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Moropa''s Gunner Sleep Bombing Set'), 'Slow Eater');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Lance Set'), 'Attack Up (M)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Lance Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Lance Set'), 'Guard +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Lance Set'), 'Detect');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Hammer Set'), 'HG Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Hammer Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Hammer Set'), 'Focus');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'No''s Hammer Set'), 'Trap Master');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'dr00''s burning offer Set'), 'Recovery Spd +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'dr00''s burning offer Set'), 'Mind''s Eye');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'dr00''s burning offer Set'), 'Focus');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'dr00''s burning offer Set'), 'Razor Sharp');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'dr00''s burning offer Set'), 'Tremor Proof');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Naked Set'), 'Focus');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Naked Set'), 'Critical Draw');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Naked Set'), 'Speed Sharpening');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Fav Set'), 'Focus');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Fav Set'), 'Recovery Spd +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Fav Set'), 'Speed Sharpening');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Yuffie''s Fav Set'), 'Trap Master');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s SnS Status Set'), 'Evasion +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s SnS Status Set'), 'Razor Sharp');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s SnS Status Set'), 'Status Atk Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Tifa''s SnS Status Set'), 'Speed Sharpening');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Very Sharp Set'), 'Attack Up (M)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Very Sharp Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Very Sharp Set'), 'Detect');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Very Sharp Set'), 'Razor Sharp');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Low Rank HGE S+1 Set'), 'HG Earplugs');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Low Rank HGE S+1 Set'), 'Sharpness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Status only gunning set'), 'Load Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Status only gunning set'), 'Recoil Down +2');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'Status only gunning set'), 'Attack Up (M)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'status only (poison) set'), 'Critical Eye +3');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'status only (poison) set'), 'Load Up');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'status only (poison) set'), 'Recoil Down +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'status only (poison) set'), 'Steadiness +1');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'aul ce+3 sharpner set'), 'Critical Eye +3');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'aul ce+3 sharpner set'), 'Attack Up (L)');
insert into set_skills (saved_set_id, label) values ((select id from saved_sets where label = 'aul ce+3 sharpner set'), 'Speed Sharpening');