ALTER TABLE saved_sets ADD USER_ID BIGINT;

CREATE TABLE users (
         ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         USERNAME VARCHAR(1024) NOT NULL,
         PASSWORD VARCHAR(1024) NOT NULL,
         
       );

ALTER TABLE saved_sets ADD FOREIGN KEY (USER_ID) REFERENCES users(ID);